#!/usr/bin/env python3
import sys


def solve(N: int, A: int, B: int):
    sum_n = 0
    for i in range(1, N+1):
        x = str(i)
        array = list(map(int, x))
        sum_x = sum(array)

        if A <= sum_x  and  sum_x <= B:
            sum_n += i

    print(sum_n)

    return


# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(N, A, B)

if __name__ == '__main__':
    main()
