#!/usr/bin/env python3


# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    word = [int(s) for s in list((input()))]
    count = 0
    for i in word:
        count += i

    print(count)
    pass

if __name__ == '__main__':
    main()
